name: misa_mobile
description: Мобильный клиент для голосового помощника «Миса»
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0                 # запросы к ПК
  speech_to_text: ^6.6.0       # распознавание речи на телефоне
  flutter_tts: ^3.8.5          # озвучка ответа на телефоне
  shared_preferences: ^2.2.2   # хранение настроек (IP, токен)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
